### ISSUE TITLE
Text "info" display incorrectly formatted on hover for small text

### ISSUE THREAD

**Issue by MarkusSagen** [zenml-io/zenml-dashboard#354]
## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General

When the UI window is small enough or when two columns have shrunken in size, the info box on hover will overlap with other text segments as show in the screenshot below 

<img width="1165" alt="Screenshot 2023-05-12 at 13 05 41" src="https://github.com/zenml-io/zenml-dashboard/assets/20767068/442ab55f-f8b2-45cf-883f-a5e0f5fc2dfd">

**Comment by Cahllagerfeld** [comment]
This is probably related to #355 and #357 and is likely to happen at other places where the component is used as well.

We're getting this fixed 👍

**Comment by ashutosh887** [comment]
@Cahllagerfeld @MarkusSagen 
I would like to work on this if needed

**Comment by Cahllagerfeld** [comment]
Sorry for my delay on this. This should be also fixed already. I'm closing the issue, in case you're still facing issues here, feel free to raise a new one, or reopen this 👍
