### ISSUE TITLE
React Flow controls for DAG Visualizers disappears on window size change

### ISSUE THREAD

**Issue by MarkusSagen** [zenml-io/zenml-dashboard#356]
## Checks

* [X] I added a descriptive title to this issue
* [X] I have searched (google, github) for similar issues and couldn't find anything
* [X] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

## General

Zoom and re-focus bottons are not scaled with the view of the browser window, meaning they sometimes are not visible or disapear when scaling the window. These should probably be sticky and follow the size of the browser window instead?

<img width="1920" alt="Screenshot 2023-05-12 at 13 55 34" src="https://github.com/zenml-io/zenml-dashboard/assets/20767068/ed720d8a-5b48-4326-a57b-d7e693d4602a">

**Comment by Cahllagerfeld** [comment]
fixed with #438
