### ISSUE TITLE
Report: Broken Links and URLs in the Repo

### ISSUE THREAD

**Issue by MarkusSagen** [zenml-io/zenml-dashboard#426]
## Report of broken URLs  

The following urls and links appear broken in the repo and their locations:

### README.md  
- [ ]  url: https://docs.zenml.io/getting-started/deploying-zenml/deploying-zenml  
- [ ]  url: https://docs.zenml.io/starter-guide/stacks/stacks  
- [ ]  url: https://docs.zenml.io/advanced-guide/stacks-components-flavors

**Comment by bcdurak** [comment]
As the new version is out, all the links should be fixed now. Closing this issue along with the others.
