### ISSUE TITLE
Full name and username cannot be edited for default account

### ISSUE THREAD

**Issue by jlopezpena** [zenml-io/zenml-dashboard#452]
Connecting to my zenml dashboard through zenml cloud, tried to edit the settings for the default account, but "Full Name" and "Server Username" still show as "default" after editing

## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

**Comment by Cahllagerfeld** [comment]
Hey @jlopezpena, 

for the default user only the password can be changed. As of now you can create a new user that "acts" like your default user if you want your username to be changed.

If you have any additional questions, feel free to ask :D, otherwise I'd close this issue 👍
