### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by jlopezpena** [zenml-io/zenml-dashboard#453]
The link to the docs in the "Repositories" tab is broken.
Clicking in the docs into "Advanced Guide" and then "Connect your git repository" leads to a "page not found" in github

## Checks

* [x] I added a descriptive title to this issue
* [x] I have searched (google, github) for similar issues and couldn't find anything
* [x] I have read and followed [the docs](https://docs.zenml.io/) and still think this is a bug

**Comment by Cahllagerfeld** [comment]
Nice catch!

I'll be fixing it! 👍

**Comment by Cahllagerfeld** [comment]
This issue should be fixed with the newest release 🙏 
Feel free to reopen if you are still running into issues here
