### ISSUE TITLE
Frontend Display Error: Member display overlaps in ZenML dashboard > settings > workspace settings

### ISSUE THREAD

**Issue by felixschroeter** [zenml-io/zenml-dashboard#536]
## Issue
After inviting additional members to my workspace, they are displayed in a way so that they overlap and are not readable anymore.
Here's a screenshot of the display error I encountered:
![image](https://github.com/zenml-io/zenml-dashboard/assets/54855386/7b31babc-6c6d-4a76-9574-48b45e585ffd)

## Browser
- Firefox 120 
- Ubuntu

Let me know if you need any further info!

**Comment by Cahllagerfeld** [comment]
Nice catch!

I'll work on fixing this 👍

**Comment by Cahllagerfeld** [comment]
I shipped the fix, it should be available with the next zenml release. I'm closing this for now 👍
