### ISSUE TITLE
ZenML Dashboard can not visualize

### ISSUE THREAD

**Issue by david101-hunter** [zenml-io/zenml-dashboard#565]
Hi team. I think it is a bug.

During the process of my experiment. Every pipeline has same problem like image below
The path for visualization is configuring correctly. However, ZenML Dashboard can not visualize
![image](https://github.com/zenml-io/zenml-dashboard/assets/156736296/f0386516-d19f-4290-b62e-8677e96e27fe)

```
../.config/zenml/local_stores/0f1a8ab4-9ffd-4579-8c5c-fe8fde54e748/get_historical_features/output/23e2241a-c545-406b-992a-b23647c600f6/98846a47/describe.csv' does not exist in artifact store 'default'.  
```
I have checked, describe.csv existed
![image](https://github.com/zenml-io/zenml-dashboard/assets/156736296/a53655e2-9e0d-4f30-8d5a-2838ae95e690)

How can I fix this? Thanks a lot!

**Comment by Cahllagerfeld** [comment]
Hello @david101-hunter, sorry for the delay 😅 
Can you please tell me if you're running this on a local or a remote server? :)

**Comment by david101-hunter** [comment]
Hi @Cahllagerfeld , I deployed self-hosted server

**Comment by Cahllagerfeld** [comment]
Okay, so just to double check, it's a remote server, with a local artifact store (assumed based on the screenshots you put there) right?

**Comment by david101-hunter** [comment]
Now, I install all of them in my personal machine, yep I'm using local artifact store

**Comment by Cahllagerfeld** [comment]
I'm a bit confused now, so it's a local server then?

**Comment by david101-hunter** [comment]
yep, local self-hosted deploy zenml

**Comment by Cahllagerfeld** [comment]
Okay, from an initial feeling this is not related to the dashboard itself, I will hand it over to a backend dev to have a look into it

**Comment by schustmi** [comment]
@david101-hunter The old dashboard is deprecated/not supported anymore, and will be removed in the `0.68.0` release of ZenML. If you encounter the same issue in the new dashboard, feel free to open up another issue!
