### ISSUE TITLE
[BUG] Visualisation glitch on HTML components

### ISSUE THREAD

**Issue by jlopezpena** [zenml-io/zenml-dashboard#588]
Testing the new dashboard on `zenml` 0.57 OSS, local server.

On of my steps yields as an output an HTML string containing a relatively large EvidentlyAI report. The visualization in the new dashboard crops the visualisation height to a fraction of the available vertical space, making it impossible to view anything (you can see the plots are cropped but there is plenty of space available below)

<img width="980" alt="image" src="https://github.com/zenml-io/zenml-dashboard/assets/3518950/0fd9af15-ab8e-4d89-9cb9-8329eec26b65">

**Comment by Cahllagerfeld** [comment]
Hello 👋

Yes, we changed the way html artifacts are visualized, because we had issues with leaking css before.
Is the height of your artifact set with css, or is it dynamically calculated with js?

**Comment by Cahllagerfeld** [comment]
Can you tell me which browser you're using

**Comment by Cahllagerfeld** [comment]
Okay, I will close it then for now. Feel free to reopen in case it reoccurs
