### ISSUE TITLE
[BUG] Visualisation glitch on HTML components (part II)

### ISSUE THREAD

**Issue by jlopezpena** [zenml-io/zenml-dashboard#589]
Some more glitches on visualisations generated from `HTMLString`:

After a feature clustering step I am plotting the resulting clusters using a `plotly` scatter plot which then gets exported to an HTML string representation. In the old dashboard the plot looks fine, in the new dashboard only the background and cluster labels can be seen, but the actual markers are not visible in the chart.

(Happy to share the code use to generate the plot privately, but cannot post it openly)

<img width="984" alt="image" src="https://github.com/zenml-io/zenml-dashboard/assets/3518950/868902a7-0299-4c9e-a721-2618bf46aab7">

**Comment by strickvl** [comment]
If you could share some dummy code to produce a similar plot / reproduce (DM via slack is fine) that'd help us, for sure! Thank you!
